export const gameConstants = {
  GAME_CREATE_REQUEST: "GAME_CREATE_REQUEST",
  GAME_CREATE_SUCCESS: "GAME_CREATE_SUCCESS",
  GAME_CREATE_FAILURE: "GAME_CREATE_FAILURE",

  GAME_UPDATE_REQUEST: "GAME_UPDATE_REQUEST",
  GAME_UPDATE_SUCCESS: "GAME_UPDATE_SUCCESS",
  GAME_UPDATE_FAILURE: "GAME_UPDATE_FAILURE",

  GAME_SQUAD_REQUEST: "GAME_SQUAD_REQUEST",
  GAME_SQUAD_SUCCESS: "GAME_SQUAD_SUCCESS",
  GAME_SQUAD_FAILURE: "GAME_SQUAD_FAILURE",

  GETALL_REQUEST: "GAMES_GETALL_REQUEST",
  GETALL_SUCCESS: "GAMES_GETALL_SUCCESS",
  GETALL_FAILURE: "GAMES_GETALL_FAILURE",

  GAME_INVITE_REQUEST: "GAME_INVITE_REQUEST",
  GAME_INVITE_SUCCESS: "GAME_INVITE_SUCCESS",
  GAME_INVITE_FAILURE: "GAME_INVITE_FAILURE",

  GAME_INVITE_RESPONSE_REQUEST: "GAME_INVITE_RESPONSE_REQUEST",
  GAME_INVITE_RESPONSE_SUCCESS: "GAME_INVITE_RESPONSE_SUCCESS",
  GAME_INVITE_RESPONSE_FAILURE: "GAME_INVITE_RESPONSE_FAILURE",

  GAME_RATING_REQUEST: "GAME_RATING_REQUEST",
  GAME_RATING_SUCCESS: "GAME_RATING_SUCCESS",
  GAME_RATING_FAILURE: "GAME_RATING_FAILURE",

  GET_RATING_REQUEST: "GET_RATING_REQUEST",
  GET_RATING_SUCCESS: "GET_RATING_SUCCESS",
  GET_RATING_FAILURE: "GET_RATING_FAILURE",

  REMOVE_GAME_REQUEST: "REMOVE_GAME_REQUEST",
  REMOVE_GAME_SUCCESS: "REMOVE_GAME_SUCCESS",
  REMOVE_GAME_FAILURE: "REMOVE_GAME_FAILURE",
};
