export const groupConstants = {
  GET_REQUEST: "GROUPS_GET_REQUEST",
  GET_SUCCESS: "GROUPS_GET_SUCCESS",
  GET_FAILURE: "GROUPS_GET_FAILURE",

  GETALL_REQUEST: "GROUPS_GETALL_REQUEST",
  GETALL_SUCCESS: "GROUPS_GETALL_SUCCESS",
  GETALL_FAILURE: "GROUPS_GETALL_FAILURE",

  GETALL_FOR_SEARCH_REQUEST: "GETALL_FOR_SEARCH_REQUEST",
  GETALL_FOR_SEARCH_SUCCESS: "GETALL_FOR_SEARCH_SUCCESS",
  GETALL_FOR_SEARCH_FAILURE: "GETALL_FOR_SEARCH_FAILURE",

  GROUP_CREATE_REQUEST: "GROUP_CREATE_REQUEST",
  GROUP_CREATE_SUCCESS: "GROUP_CREATE_SUCCESS",
  GROUP_CREATE_FAILURE: "GROUP_CREATE_FAILURE",

  GROUP_UPDATE_REQUEST: "GROUP_UPDATE_REQUEST",
  GROUP_UPDATE_SUCCESS: "GROUP_UPDATE_SUCCESS",
  GROUP_UPDATE_FAILURE: "GROUP_UPDATE_FAILURE",

  EDIT_MEMBER_REQUEST: "EDIT_MEMBER_REQUEST",
  EDIT_MEMBER_SUCCESS: "EDIT_MEMBER_SUCCESS",
  EDIT_MEMBER_FAILURE: "EDIT_MEMBER_FAILURE",

  LEAVE_GROUP_REQUEST: "LEAVE_GROUP_REQUEST",
  LEAVE_GROUP_SUCCESS: "LEAVE_GROUP_SUCCESS",
  LEAVE_GROUP_FAILURE: "LEAVE_GROUP_FAILURE",

  GROUP_JOIN_REQUEST: "GROUP_JOIN_REQUEST",
  GROUP_JOIN_SUCCESS: "GROUP_JOIN_SUCCESS",
  GROUP_JOIN_FAILURE: "GROUP_JOIN_FAILURE",

  GROUP_INVITE_REQUEST: "GROUP_INVITE_REQUEST",
  GROUP_INVITE_SUCCESS: "GROUP_INVITE_SUCCESS",
  GROUP_INVITE_FAILURE: "GROUP_INVITE_FAILURE",

  REMOVE_GROUP_REQUEST: "REMOVE_GROUP_REQUEST",
  REMOVE_GROUP_SUCCESS: "REMOVE_GROUP_SUCCESS",
  REMOVE_GROUP_FAILURE: "REMOVE_GROUP_FAILURE",

  REMOVE_FROM_GROUP_REQUEST: "REMOVE_FROM_GROUP_REQUEST",
  REMOVE_FROM_GROUP_SUCCESS: "REMOVE_FROM_GROUP_SUCCESS",
  REMOVE_FROM_GROUP_FAILURE: "REMOVE_FROM_GROUP_FAILURE",
};
