export const userConstants = {
  REGISTER_REQUEST: "USERS_REGISTER_REQUEST",
  REGISTER_SUCCESS: "USERS_REGISTER_SUCCESS",
  REGISTER_FAILURE: "USERS_REGISTER_FAILURE",

  LOGIN_REQUEST: "USERS_LOGIN_REQUEST",
  LOGIN_SUCCESS: "USERS_LOGIN_SUCCESS",
  LOGIN_FAILURE: "USERS_LOGIN_FAILURE",

  FORGET_PASSWORD_REQUEST: "USERS_FORGET_PASSWORD_REQUEST",
  FORGET_PASSWORD_SUCCESS: "USERS_FORGET_PASSWORD_SUCCESS",
  FORGET_PASSWORD_FAILURE: "USERS_FORGET_PASSWORD_FAILURE",

  LOGOUT: "USERS_LOGOUT",

  GETALL_FOR_SQUAD_REQUEST: "GETALL_FOR_SQUAD_REQUEST",
  GETALL_FOR_SQUAD_SUCCESS: "GETALL_FOR_SQUAD_SUCCESS",
  GETALL_FOR_SQUAD_FAILURE: "GETALL_FOR_SQUAD_FAILURE"
};
